### ISSUE TITLE
Add icon to desktop entry

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#10]
initial look-see

.desktop file doesnt have an icon associated with it - looks odd in the menu

the .desktop needs a "OnlyShowIn=Budgie;" so that it only launches for a budgie-desktop session

**Comment by niyasc** [comment]
Icon for **Welcome App** is mentioned by `Icon=gtk-info` in  `.desktop` file.

In other welcome apps, it is written as `Icon=distroname` and all major distributions have corresponding icons in theme pack. 

So, I think we should first push our distribution icon to icon theme and then update `.desktop` file accordingly.

**Comment by fossfreedom** [comment]
k - we'll do this on a subsequent update to the app.  Thanks for the info.

**Comment by Foggalong** [comment]
The iteration of the app included in the beta [has an icon line](https://github.com/budgie-remix/budgie-welcome/blob/master/budgie-welcome.desktop#L8) but it's hardcoded so we can't theme it.

**Comment by HEXcube** [comment]
The [hardcoded icon line in budgie-welcome.desktop](https://github.com/budgie-remix/budgie-welcome/blob/v0.3.12/budgie-welcome.desktop#L8) was fixed by @fossfreedom in two previous commits https://github.com/budgie-remix/budgie-welcome/commit/154cb2f5de22b6586137879f5bf9884866684067 and https://github.com/budgie-remix/budgie-welcome/commit/16fef014ce31547709de1f1f0c9d57c137acfa2c . :smiley:

The [icon line in budgie-welcom.desktop](https://github.com/budgie-remix/budgie-welcome/blob/16fef014ce31547709de1f1f0c9d57c137acfa2c/budgie-welcome.desktop#L8) isn't hardcoded anymore and the icon's placed in the proper location `/usr/share/icons/hicolor/scalable/places/distributor-logo-budgie-remix.svg`. So, I'm closing this issue
