### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by Udara-U3** [budgie-remix/budgie-welcome#18]
- First thing is Welcome app **can't move anywhere**, should make that top bar as a title bar.

![screenshot from 2016-07-21 22-53-00](https://cloud.githubusercontent.com/assets/12265797/17035866/c5a4bb4e-4f9a-11e6-8988-8b7f513d339f.png)
- I can see **Open source icon is overlapped** with text so we have to fix it.
  And right top we can see little white space, It's scroll bar. We should move it in the below of Top bar. So it would be nicer.

![screenshot from 2016-07-21 22-58-55](https://cloud.githubusercontent.com/assets/12265797/17035962/292177c0-4f9b-11e6-8deb-9758f1a4d82c.png)
- As @HEXcube Made some button improvements before, this button is also have to improve **aligning text to the middle of the button**.

![screenshot from 2016-07-21 23-00-20](https://cloud.githubusercontent.com/assets/12265797/17036003/5ff82c8a-4f9b-11e6-9114-30a70e76c8bb.png)
- **Snap** should be the first recommendation. ( Move to top )

![screenshot from 2016-07-21 23-00-52](https://cloud.githubusercontent.com/assets/12265797/17036030/82247a52-4f9b-11e6-8312-257565f2fbc6.png)
- **Twitter icon** is missing in this Community page and We can use Inverted budgie-remix logo instead of Original icon for the Button.

![screenshot from 2016-07-21 23-02-56](https://cloud.githubusercontent.com/assets/12265797/17036068/b3725048-4f9b-11e6-9764-62848c287be3.png)
- We can Also add budgie-remix website Opportunities page to **Get Involved** page

![screenshot from 2016-07-21 23-03-09](https://cloud.githubusercontent.com/assets/12265797/17036101/d86c5a4c-4f9b-11e6-872b-461b10ad120a.png)
- So finally, in this donate page we can use Official donate buttons with bit enlarge size instead of this small normal buttons

**Comment by niyasc** [comment]
In order to track progress easily, suggestions made by @Udara-U3 are listed here. If there is any additional suggestion on **UI improvement**, update this comment.
**Global**
- **Welcome App** window should be movable - (No idea, how to implement this feature. Either we need to restore window decorations or use some non-traditional ways to move window, for example press a key and drag.)

**Introduction**
- `Open Source` logo should not overlap with text.

**Getting Started - Updates & Extras**
- `center` align text on buttons.

**Recommendation**
- Snap should be first item listed in recommendations - **DONE**

**Community**
- Add twitter icon & link
- Update G+ icon to include both page and community
- Use inverted `budgie-remix` icon with button.

**Get Involved**
- Add **opportunities** and provide link to corresponding page in website.

**Donate**
- Use official banners instead of traditional buttons, and use it in enlarged size.

**Comment by niyasc** [comment]
Seems that, this functionality is not that difficult to implement. One important concern should be, how to place these updates on index page without looking weird.

**Comment by fossfreedom** [comment]
ok - consider this one closed.
