### ISSUE TITLE
various hyperlinks and button links dont work

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#21]
1. System Specifications there is a hyperlink that doesnt seem to do anything - "Why do I see two units"
2. similarly "Raven" in Recommendations - should this be a hyperlink?
3. all the hyperlinks on the "Get Involved" page crash and burn.
4. Raven Control Center button on Getting Started - Customisation doesnt do anything

**Comment by niyasc** [comment]
This issue is addressed by commit https://github.com/budgie-remix/budgie-welcome/commit/92b1a0b0775df2fcb8bdbc390b927ccd15a95975

1. Removed broken link from system specifications.
2. Made 'raven' link functional. This assumes that `xdotool` is  available in system.
3. Fixed all links in "Get Involved" page
4. Action on 2 fixes this problem.
